name: Trigger auto deployment for pihole

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'test/**'
    - '.github/workflows/pihole-AutoDeployTrigger-21d25d98-c68d-4da7-9a6f-6a0d215ebf9f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: github.com/pi-hole/docker-pi-hole
          username: ${{ secrets.PIHOLE_REGISTRY_USERNAME }}
          password: ${{ secrets.PIHOLE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: github.com/pi-hole/docker-pi-hole/pihole:${{ github.sha }}
          file: test/Dockerfile
          context: test/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PIHOLE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n pihole -g Imrul --server github.com/pi-hole/docker-pi-hole --username  ${{ secrets.PIHOLE_REGISTRY_USERNAME }} --password ${{ secrets.PIHOLE_REGISTRY_PASSWORD }}
            az containerapp update -n pihole -g Imrul --image github.com/pi-hole/docker-pi-hole/pihole:${{ github.sha }}
